### ISSUE TITLE
rebranding

### ISSUE THREAD

**Issue by brenzi** [integritee-network/sgx-runtime#11]
replace all SubstraTEE by Integritee. Modify  Copyright notice to include both SCS and Integritee AG

example
https://github.com/integritee-network/pallet-teerex/blob/2b5ab50435b6dadcb033a562977196ccbe72f7ef/src/lib.rs#L2-L14

**Comment by echevrier** [comment]
There is no Copyright notice of this form. Shall I add the notice to the different src files?

**Comment by echevrier** [comment]
Supercomputing is only mentiones as author. Shall I update it? And the repository link simultaneously?

**Comment by echevrier** [comment]
To fix later : 

- https://www.substratee.com in Readme. See comment in book issue 9: https://github.com/integritee-network/book/issues/9#issuecomment-901826134 
-  the build.yml for the docker: See above comment in book

**Comment by echevrier** [comment]
Replace libsubstratee_worker_enclave.a  in Makefile when  [#348](https://github.com/integritee-network/worker/issues/348) is done.

**Comment by echevrier** [comment]
`author("Supercomputing Systems AG <info@scs.ch>")` becomes `author("Integritee AG <hello@integritee.network>")` according to https://github.com/integritee-network/worker/pull/378#discussion_r699384803

**Comment by clangenb** [comment]
> 
> 
> What to do with:
> libsubstratee_worker_enclave.a in Makefile ?

This make file is copy-pasted from the worker. The copy line does not make sense here at all. So, you can simply delete these two lines from the Makefile.

**Comment by clangenb** [comment]
I have only seen now that there is one more unanswered question:

Yes, add the copyright headers to all the source files. Only `sp-io/without_sgx` should be left as is. This is 100% copy-pasted from substrate.

I will make a separate issue about removing the `without-sgx` entirely, this should not be necessary anymore.
