### ISSUE TITLE
remove `without-sgx` in sp-io

### ISSUE THREAD

**Issue by clangenb** [integritee-network/sgx-runtime#19]
I think with our current setup. We only need the `with-sgx` part of `sp-io`. With the current cargo setup, there is anyhow no way to compile it to std. Furthermore, this is an exact copy of substrate's version.

Hence, dependants that should be able to compile to std, can simply do something like:

```
[features]
std = [
   "sp-io"
]
sgx = [
     "sgx-sp-io"
]
```

**Comment by brenzi** [comment]
We should just add a note in this repo's README about how to build it separately. People have been confused by the fact that cargo build does not work

**Comment by mullefel** [comment]
This should be solved by #30, `sp-io` can be compiled for both `sgx` and `std` and removed the `without-sgx.rs`
