### ISSUE TITLE
[sgx-externalities]  compiles to std + move integritee-workers tests to here.

### ISSUE THREAD

**Issue by clangenb** [integritee-network/sgx-runtime#23]
And execute them with cargo test in integration tests.

**Comment by brenzi** [comment]
Which tests would you move here and why?

**Comment by clangenb** [comment]
There are tests that check athe encode decode for externalities types. They are, in fact, failing since my upgrade here.

**Comment by mullefel** [comment]
#30 solves the first part, of compiling externalities to `std`.

**Comment by mullefel** [comment]
Closed, as sgx-runtime and externalities crates are moved back to the worker.
