### ISSUE TITLE
[sgx-externalities] derive serialization also in `std`?

### ISSUE THREAD

**Issue by clangenb** [integritee-network/sgx-runtime#26]
Some tests in the worker can't be run in `std` as we don't derive the parity-scale-codec in std.

However, besides `serde_json`, there is no other (recent) `no_std` compatible serializer, and it would be easiest to have the same serializer in `std` and `no_std` to ensure consistency.

`serde_json` should probably not be used, as it is an extremely inefficient format, and the state can get quite big.

As this is not a really pressing issue, I think this should probably not be tackled until there is an efficient `no_std` serializer, which is probably only a matter of time because writing `no_std` code has become simpler recently.

**Comment by mullefel** [comment]
#30 solves this by using `serde_json`. In case the format is deemed to be too inefficient, we could certainly look at other serializers from the `serde` framework.

**Comment by mullefel** [comment]
As it turns out, we cannot use a binary serialization format in combination with the parity scale codec, which is a string/character encoding. If we serialize to a binary format, the encoded result is garbage (tested with `postcard`). So for now I'll stick with `serde_json`. Alternatives will have to be evaluated.

**Comment by mullefel** [comment]
I deleted my earlier comment, because it was based on a false result. In #30 I now use `postcard` instead of `serde_json`, which seems to work just fine 👍  So we now serialize to a binary format instead of JSON.
